### ISSUE TITLE
OpenAI回复逻辑 补全

### ISSUE THREAD

**Issue by Gin2O** [Gin2O/nonebot_plugin_oachat#1]
在调用 `openai api` 进行提问的时候，如果问题语义不清楚，openai会将问题补全并返回，导致输出结果不整洁。
比如下方我提问 “目录学” ，本意应当是问“目录学”的名词解释，但是openai会认为问题不明确，并将问题补全为 “目录学习” 。

- eg：

  - Gin2O：/chat 目录学

  - OpenAI：

    - > 习
      >  §§ 1001
      > +## 一、概念
      > +
      > +树状数据结构是指一种数据结构，它有一个根节点，其余节点分成若干不相交的子树，每个节点有一个父节点，每个节点可以有一个或多个子节点 。
      > +
      > +树状数据结构是一种重要的数据结构，它主要用于实现信息组织、信息检索和信息处理等功能。树状结构在信息处理中，用于表示多层次的信息关系，在搜索中，用于表示信息的层次结构，在网络管理中，用于表示网络层次结构，在文件系统中，用于表示文件存储的目录结构，在数据库管理系统中，用于表示数据库的存储结构，在算法设计中，用于表示算法的递归结构等。
      > +
      > +## 二、特点
      > +
      > +1. 非线性结构：树状数据结构是一种非线性结构，它不是由一系列顺序排列的链表或数组组成的，而是由一组父子节点组成的多叉树。
      > +2. 非常规结构：树状数据结构与其他常规的数据结构有很大的不同，比如树状结构不支持随机访问，而其他常规数据结构支持随机访问，树状结构还有可能存在子节点多于父节点的情况，而其他常规数据结构没有这种情况。
      > +3. 多叉树：树状数据结构是一种多叉树，它的每个节点有多个子节点

**Comment by Gin2O** [comment]
值得注意的是
使用中文问题提问时，补全问题使用的字数都比较少，或者补全“？”。
但是收到中文回复的时候，字数似乎往往远大于补全问题的字数。

或许可以用回答的字数长度做一个筛选？

**Comment by Gin2O** [comment]
现在已经用正则匹配实现了问题补全，还在测试功能
- 中文问题正则框架✔️
- 英文问题正则框架✔️

**Comment by YumeAyai** [comment]
哥们，源码没脱敏

**Comment by Gin2O** [comment]
> 哥们，源码没脱敏

感谢提醒，我已经重置的openai key，不知道是否有效
